# Generated by Django 4.0.5 on 2022-06-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_cars_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['rating'], 'verbose_name': 'La Pagina Web', 'verbose_name_plural': 'Las Paginas Webs'},
        ),
    ]
